"""add_groups_table

Revision ID: 4e7a13ef134b
Revises: 8c5aaa4b77ed
Create Date: 2025-11-05 00:34:51.547656

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4e7a13ef134b'
down_revision: Union[str, Sequence[str], None] = '8c5aaa4b77ed'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Create groups table if it doesn't exist
    connection = op.get_bind()
    inspector = sa.inspect(connection)
    tables = inspector.get_table_names()
    
    if 'groups' not in tables:
        op.create_table(
            'groups',
            sa.Column('id', sa.Integer(), nullable=False),
            sa.Column('name', sa.String(length=128), nullable=False),
            sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
            sa.PrimaryKeyConstraint('id')
        )
        op.create_index(op.f('ix_groups_id'), 'groups', ['id'], unique=False)
        op.create_index(op.f('ix_groups_name'), 'groups', ['name'], unique=True)
    
    # Add group_id column to words
    op.add_column('words', sa.Column('group_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_words_group_id'), 'words', ['group_id'], unique=False)
    op.create_foreign_key(None, 'words', 'groups', ['group_id'], ['id'], ondelete='SET NULL')
    
    # Populate groups from existing words
    connection = op.get_bind()
    # Get all unique group names from words
    result = connection.execute(sa.text("SELECT DISTINCT group_name FROM words WHERE group_name IS NOT NULL AND group_name != ''"))
    group_names = [row[0] for row in result]
    
    # Insert groups and update words.group_id
    group_map = {}
    for group_name in group_names:
        # Insert group
        result = connection.execute(
            sa.text("INSERT INTO groups (name) VALUES (:name) ON CONFLICT (name) DO NOTHING RETURNING id"),
            {"name": group_name}
        )
        row = result.fetchone()
        if row:
            group_map[group_name] = row[0]
        else:
            # Group already exists, get its id
            result = connection.execute(
                sa.text("SELECT id FROM groups WHERE name = :name"),
                {"name": group_name}
            )
            row = result.fetchone()
            if row:
                group_map[group_name] = row[0]
    
    # Update words.group_id from group_name
    for group_name, group_id in group_map.items():
        connection.execute(
            sa.text("UPDATE words SET group_id = :group_id WHERE group_name = :group_name"),
            {"group_id": group_id, "group_name": group_name}
        )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'words', type_='foreignkey')
    op.drop_index(op.f('ix_words_group_id'), table_name='words')
    op.drop_column('words', 'group_id')
    op.drop_index(op.f('ix_groups_name'), table_name='groups')
    op.drop_index(op.f('ix_groups_id'), table_name='groups')
    op.drop_table('groups')
    # ### end Alembic commands ###
